/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package net.deadbeat.main;

import net.deadbeat.components.CoreOverlayPanel;
import net.deadbeat.components.CorePanel;
import java.awt.Dimension;
import java.awt.event.ComponentAdapter;
import java.awt.event.ComponentEvent;
import java.awt.geom.RoundRectangle2D;
import javax.swing.JFrame;

/**
 *
 * @author darylcecile
 */
public class Home extends javax.swing.JFrame {

    /**
     * Creates new form Home
     */
    public Home() {
        initFrames();
    }
    
    protected CorePanel corepanel;
    protected CoreOverlayPanel overlaypanel;
    
    private void initFrames(){
        
        this.setLayout(new RawLayout());
        
        corepanel = new CorePanel();
        overlaypanel = new CoreOverlayPanel();
        
        corepanel.setLayout( new RelativeLayout(corepanel,overlaypanel,this) );
        
        setUndecorated(true);
        JFrame.setDefaultLookAndFeelDecorated(false);
        
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        add(corepanel);

        this.setSize(900,640);
        this.setMinimumSize(new Dimension(900,640));
        this.setPreferredSize(new Dimension(900,640));

        int ow = (getWidth()/100) * 22;
        corepanel.setDimension(getWidth(), getHeight());
        
        overlaypanel.setPosition( ow , 20 );
        overlaypanel.setDimension( getWidth() - ow , getContainerHeight() );
        
        corepanel.add(overlaypanel);
        
        setShape(new RoundRectangle2D.Double(20, 20, getWidth() - 20, getContainerHeight(), 6, 6));
        
     
        this.getRootPane().addComponentListener(new ComponentAdapter() {
            @Override
            public void componentResized(ComponentEvent e) {
                // force update the dimensions so panel can update graphics
                int sidebarWidth = (getWidth()/100) * 25;
                corepanel.setDimension(getWidth(), getHeight());
                overlaypanel.setPosition( sidebarWidth , 20 );
                overlaypanel.setDimension( getWidth() - sidebarWidth , getContainerHeight() );
                
                ( (RelativeLayout)corepanel.getLayout() ).performLayout();
            }
        });
        
        System.out.println("Frame Initialized");

        initComponents();
       
    }
    
    public int getContainerHeight(){
        // remove bit where titlebar usually resides
        return getHeight() - 20;
    }
    
    public int getContainerWidth(){
        return getWidth();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
